name: checkov-bridgecrew

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: terraform-scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Checkov Terraform Scan
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
          download_external_modules: true
          github_pat: ${{ secrets.GH_PAT }}
        env:
          GITHUB_OVERRIDE_URL: true  # optional: this can be used to instruct the action to override the global GIT config to inject the PAT to the URL

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif
